/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f411re.h"
#include "stm32f411re_gpio_driver.h"

__vo uint8_t g_button_flag = RESET;
__vo uint8_t g_led1_flag   = RESET;
__vo uint8_t g_led2_flag   = RESET;
__vo uint8_t g_led3_flag   = RESET;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
    for (uint32_t i = 0; i < 500000; i++);
}

void GPIO_PinConfig(void)
{
    GPIO_DigitalPin(GPIO_MODE_OUT, GPIOA, GPIO_PIN5);    // USER_LED
    GPIO_DigitalPin(GPIO_MODE_IT_FT, GPIOC, GPIO_PIN13); // USER_BTN
    GPIO_DigitalPin(GPIO_MODE_OUT, GPIOA, GPIO_PIN8);    // LED RED
    GPIO_DigitalPin(GPIO_MODE_OUT, GPIOA, GPIO_PIN9);    // LED GREEN
    GPIO_DigitalPin(GPIO_MODE_OUT, GPIOC, GPIO_PIN8);    // BUZZER
    NVIC_IRQConfig(EXTI15_10_IRQn, ENABLE);
}

int main(void)
{
    Systick_Init(1);
    GPIO_PinConfig();
    /* Loop forever */
    while (1)
    {
        if (g_button_flag)
        {
            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN5);
            g_button_flag = RESET;
        }
        if (g_led1_flag >= 3)
        {
            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN8);
            g_led1_flag = RESET;
        }
        if (g_led2_flag >= 5)
        {
            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN9);
            g_led2_flag = RESET;
        }
    }
}

void EXTI15_10_IRQHandler()
{
    GPIO_IRQHandling(GPIO_PIN13);
    g_button_flag = SET;
}

void SysTick_Handler()
{
    g_led1_flag++;
    g_led2_flag++;
    g_led3_flag++;
}
