/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f411re.h"
#include "stm32f411re_gpio_driver.h"

__vo uint8_t g_button_flag = RESET;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
    for (uint32_t i = 0; i < 500000; i++);
}

void GPIO_PinConfig(void)
{
    GPIO_DigitalPin(GPIO_MODE_OUT, GPIOA, GPIO_PIN5);
    GPIO_DigitalPin(GPIO_MODE_IT_FT, GPIOC, GPIO_PIN13);
    NVIC_IRQConfig(IRQ_NO_EXTI15_10, ENABLE);
}

int main(void)
{
    GPIO_PinConfig();

    /* Loop forever */
    while (1)
    {
        if (g_button_flag)
        {
            GPIO_ToggleOutputPin(GPIOA, GPIO_PIN5);
            g_button_flag = RESET;
        }
    }
}

void EXTI15_10_IRQHandler()
{
    GPIO_IRQHandling(GPIO_PIN13);
    g_button_flag = SET;
}